repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.278
  hooks:
  - id: ruff

- repo: https://github.com/ambv/black
  rev: 23.7.0
  hooks:
  - id: black
    language_version: python3.11
