[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"

[tool.ruff]
line-length = 140
select = ["E", "F", "I"]

[tool.black]
line-length = 140
target-version = ['py31!']

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
