require("baitholder.lazy")
require("baitholder.core.colors")
require("baitholder.core.options")
require("baitholder.core.keymaps")
require("baitholder.plugins.telescope")
require("baitholder.plugins.vimtex")
require("baitholder.plugins.comment")
require("baitholder.plugins.copilot")
-- require("baitholder.plugins.refactoring")
require("baitholder.plugins.harpoon")
require("baitholder.plugins.treesitter")
-- require("baitholder.plugins.undotree")
-- require("baitholder.plugins.fugitive")
-- require("baitholder.plugins.trouble")
require("baitholder.plugins.lsp.cmp")
require("baitholder.plugins.lsp.lsp")
--
-- require("baitholder.plugins.rust")
require("baitholder.plugins.debug")
require("baitholder.plugins.dap")
